sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile -t docker-react . 

script:
  - docker run docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: DockerReact
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-221344413720"
  bucket_path: "DockerReact-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"  
